# Generated by Django 3.2.10 on 2022-05-26 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(max_length=255)),
                ('first_published_at', models.DateTimeField(null=True)),
                ('last_published_at', models.DateTimeField(null=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.learningcontext')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemstore.item')),
                ('item_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='itemstore.iteminfo')),
            ],
        ),
        migrations.CreateModel(
            name='LearningContextVersionItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='itemstore.itemversion')),
                ('learning_context_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.learningcontextversion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_digest', models.CharField(editable=False, max_length=40)),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('created', models.DateTimeField()),
                ('data', models.BinaryField()),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.learningcontext')),
            ],
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='item_raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='itemstore.itemraw'),
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.learningcontext'),
        ),
        migrations.AddField(
            model_name='item',
            name='published_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='itemstore.itemversion'),
        ),
        migrations.AddConstraint(
            model_name='itemraw',
            constraint=models.UniqueConstraint(fields=('learning_context_id', 'mime_type', 'hash_digest'), name='learning_publishing_item_raw_uniq_lc_hd'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('learning_context_id', 'identifier'), name='learning_publishing_lcb_one_identifier_per_lc'),
        ),
    ]
