# This is a Code Annotations automatically-generated Django model safelist file.
# These models must be annotated as follows in order to be counted in the coverage report.
# See https://code-annotations.readthedocs.io/en/latest/safelist.html for more information.
#
# fake_app_1.FakeModelName:
#    ".. no_pii:": "This model has no PII"
# fake_app_2.FakeModel2:
#    ".. choice_annotation:": foo, bar, baz

admin.LogEntry:
  ".. no_pii:": "This model has no PII"
auth.Group:
  ".. no_pii:": "This model has no PII"
auth.Permission:
  ".. no_pii:": "This model has no PII"
auth.User:
  ".. pii": "This model minimally contains a username, password, and email"
  ".. pii_types": "username, email_address, password"
  ".. pii_retirement": "consumer_api"
contenttypes.ContentType:
  ".. no_pii:": "This model has no PII"
oel_authoring.Collection:
  ".. no_pii:": "This model has no PII"
oel_authoring.CollectionPublishableEntity:
  ".. no_pii:": "This model has no PII"
oel_authoring.Component:
  ".. no_pii:": "This model has no PII"
oel_authoring.ComponentType:
  ".. no_pii:": "This model has no PII"
oel_authoring.ComponentVersion:
  ".. no_pii:": "This model has no PII"
oel_authoring.ComponentVersionContent:
  ".. no_pii:": "This model has no PII"
oel_authoring.Content:
  ".. no_pii:": "This model has no PII"
oel_authoring.MediaType:
  ".. no_pii:": "This model has no PII"
oel_authoring.Container:
  ".. no_pii:": "This model has no PII"
oel_authoring.ContainerVersion:
  ".. no_pii:": "This model has no PII"
oel_authoring.Draft:
  ".. no_pii:": "This model has no PII"
oel_authoring.EntityList:
  ".. no_pii:": "This model has no PII"
oel_authoring.EntityListRow:
  ".. no_pii:": "This model has no PII"
oel_authoring.LearningPackage:
  ".. no_pii:": "This model has no PII"
oel_authoring.PublishLog:
  ".. no_pii:": "This model has no PII"
oel_authoring.PublishLogRecord:
  ".. no_pii:": "This model has no PII"
oel_authoring.PublishableEntity:
  ".. no_pii:": "This model has no PII"
oel_authoring.PublishableEntityVersion:
  ".. no_pii:": "This model has no PII"
oel_authoring.Published:
  ".. no_pii:": "This model has no PII"
oel_tagging.ObjectTag:
  ".. no_pii:": "This model has no PII"
oel_tagging.Tag:
  ".. no_pii:": "This model has no PII"
oel_tagging.TagImportTask:
  ".. no_pii:": "This model has no PII"
oel_tagging.Taxonomy:
  ".. no_pii:": "This model has no PII"
oel_authoring.Section:
  ".. no_pii:": "This model has no PII"
oel_authoring.SectionVersion:
  ".. no_pii:": "This model has no PII"
oel_authoring.Subsection:
  ".. no_pii:": "This model has no PII"
oel_authoring.SubsectionVersion:
  ".. no_pii:": "This model has no PII"
oel_authoring.Unit:
  ".. no_pii:": "This model has no PII"
oel_authoring.UnitVersion:
  ".. no_pii:": "This model has no PII"
social_django.Association:
  ".. no_pii:": "This model has no PII"
social_django.Code:
  ".. pii:": "Email address"
  ".. pii_types:": other
  ".. pii_retirement:": local_api
social_django.Nonce:
  ".. no_pii:": "This model has no PII"
social_django.Partial:
  ".. no_pii:": "This model has no PII"
social_django.UserSocialAuth:
  ".. no_pii:": "This model has no PII"
sessions.Session:
  ".. no_pii:": "This model has no PII"
waffle.Flag:
  ".. no_pii:": "This model has no PII"
waffle.Sample:
  ".. no_pii:": "This model has no PII"
waffle.Switch:
  ".. no_pii:": "This model has no PII"
