# Generated by Django 5.2.9 on 2025-12-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oel_authoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collection',
            new_name='oel_authoring_coll_lp_title',
            old_name='oel_collect_learnin_dfaf89_idx',
        ),
        migrations.AlterModelTable(
            name='collection',
            table=None,
        ),
        migrations.AlterModelTable(
            name='collectionpublishableentity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='component',
            table=None,
        ),
        migrations.AlterModelTable(
            name='componenttype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='componentversion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='componentversioncontent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='container',
            table=None,
        ),
        migrations.AlterModelTable(
            name='containerversion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='draft',
            table=None,
        ),
        migrations.AlterModelTable(
            name='draftchangelog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='draftchangelogrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='draftsideeffect',
            table=None,
        ),
        migrations.AlterModelTable(
            name='entitylist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='entitylistrow',
            table=None,
        ),
        migrations.AlterModelTable(
            name='learningpackage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publishableentity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publishableentityversion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publishableentityversiondependency',
            table=None,
        ),
        migrations.AlterModelTable(
            name='published',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publishlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publishlogrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publishsideeffect',
            table=None,
        ),
    ]
