# Generated by Django 5.2.11 on 2026-02-10 03:08

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import opaque_keys.edx.django.models
from django.db import migrations, models

import openedx_catalog.models.catalog_course
import openedx_django_lib.fields
import openedx_django_lib.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_auto_20230727_2054"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        help_text="The internal database ID for this catalog course. Should not be exposed to users nor in APIs.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Primary Key",
                    ),
                ),
                (
                    "course_code",
                    openedx_django_lib.fields.MultiCollationCharField(
                        db_collations={"mysql": "utf8mb4_bin", "sqlite": "BINARY"},
                        help_text='The course code/number, e.g. "Math100".',
                        max_length=255,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, validators=[openedx_django_lib.validators.validate_utc_datetime]
                    ),
                ),
                (
                    "title",
                    openedx_django_lib.fields.MultiCollationCharField(
                        db_collations={"mysql": "utf8mb4_unicode_ci", "sqlite": "NOCASE"},
                        help_text='The full title (display name) of this catalog course. e.g. "Introduction to Calculus". Individual course runs may override this, e.g. "Intro to Calc (Fall 2026 with Dr. Newton)".',
                        max_length=255,
                    ),
                ),
                (
                    "language",
                    openedx_django_lib.fields.MultiCollationCharField(
                        db_collations={"mysql": "utf8mb4_bin", "sqlite": "BINARY"},
                        default=openedx_catalog.models.catalog_course.get_default_language_code,
                        help_text='The code representing the primary language of this catalog course\'s content - the language in which the content is authored and which learners can learn without translation. (Translated versions of the course or parts of the course may be available in other languages if supported by the platform.) The first two digits must be the lowercase ISO 639-1 language code, optionally followed by a country/locale code. e.g. "en", "es", "fr-ca", "pt-br", "zh-cn", "zh-hk". ',
                        max_length=64,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"),
                ),
            ],
            options={
                "verbose_name": "Catalog Course",
                "verbose_name_plural": "Catalog Courses",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="CourseRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False,
                        help_text="The internal database ID for this course. Should not be exposed to users nor in APIs.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Primary Key",
                    ),
                ),
                (
                    "course_key",
                    opaque_keys.edx.django.models.CourseKeyField(
                        case_sensitive=True,
                        db_index=True,
                        editable=False,
                        help_text="The main identifier for this course. Includes the org, course code, and run.",
                        max_length=255,
                        verbose_name="Course Key",
                    ),
                ),
                (
                    "run_code",
                    openedx_django_lib.fields.MultiCollationCharField(
                        db_collations={"mysql": "utf8mb4_bin", "sqlite": "BINARY"},
                        help_text='The code that identifies this particular run of the course, e.g. "2026", "2026Fall" or "2T2026"',
                        max_length=128,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, validators=[openedx_django_lib.validators.validate_utc_datetime]
                    ),
                ),
                (
                    "title",
                    openedx_django_lib.fields.MultiCollationCharField(
                        blank=True,
                        db_collations={"mysql": "utf8mb4_unicode_ci", "sqlite": "NOCASE"},
                        help_text='The full title (display name) of this course. e.g. "Introduction to Calculus". This is required and will override the title of the catalog course. Leave blank to use the same title as the catalog course. ',
                        max_length=255,
                    ),
                ),
                (
                    "catalog_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="openedx_catalog.catalogcourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Run",
                "verbose_name_plural": "Course Runs",
                "ordering": ("-created",),
            },
        ),
        migrations.AddIndex(
            model_name="catalogcourse",
            index=models.Index(fields=["org", "course_code"], name="openedx_cat_org_id_bd314b_idx"),
        ),
        migrations.AddConstraint(
            model_name="catalogcourse",
            constraint=models.UniqueConstraint(
                models.F("org"),
                django.db.models.functions.text.Lower("course_code"),
                name="oex_catalog_catalogcourse_org_code_uniq_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogcourse",
            constraint=models.CheckConstraint(
                condition=models.Q(("course_code__length__gt", 0)),
                name="oex_catalog_catalogcourse_course_code_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogcourse",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__length__gt", 0)), name="oex_catalog_catalogcourse_title_not_blank"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogcourse",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Regex(models.F("language"), "^[a-z][a-z](\\-[a-z0-9]+)*$"),
                name="oex_catalog_catalogcourse_language_regex",
                violation_error_message='The language code must be lowercase, e.g. "en". If a country/locale code is provided, it must be separated by a hyphen, e.g. "en-us", "zh-hk". ',
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.UniqueConstraint(
                models.F("catalog_course"),
                models.F("run_code"),
                condition=models.Q(("course_key__startswith", "ccx"), _negated=True),
                name="oex_catalog_courserun_catalog_course_run_code_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("course_key"), name="oex_catalog_courserun_course_key_ci"
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.CheckConstraint(
                condition=models.Q(("run_code__length__gt", 0)), name="oex_catalog_courserun_run_code_not_blank"
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__length__gt", 0)), name="oex_catalog_courserun_title_not_blank"
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.GreaterThan(
                    django.db.models.functions.text.StrIndex("course_key", models.F("run_code")), 0
                ),
                name="oex_catalog_courserun_course_key_run_code_match_exactly",
                violation_error_message="The CourseRun 'run_code' field should match the run in the 'course_key'.",
            ),
        ),
    ]
