# Generated by Django 5.2 on 2025-04-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0004_publishableentity_can_stand_alone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitylistrow',
            options={'ordering': ['order_num']},
        ),
    ]
