# Generated by Django 4.1 on 2023-02-06 00:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("namespace", models.CharField(max_length=100)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("identifier", models.CharField(max_length=255)),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                (
                    "learning_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing.learningpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created", models.DateTimeField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.component",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash_digest", models.CharField(editable=False, max_length=40)),
                ("type", models.CharField(max_length=127)),
                ("sub_type", models.CharField(max_length=127)),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MaxValueValidator(10000000)]
                    ),
                ),
                ("created", models.DateTimeField()),
                ("data", models.BinaryField(max_length=10000000)),
                (
                    "learning_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing.learningpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentVersionContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "component_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.componentversion",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.content",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="componentversion",
            name="contents",
            field=models.ManyToManyField(
                related_name="component_versions",
                through="components.ComponentVersionContent",
                to="components.content",
            ),
        ),
        migrations.CreateModel(
            name="ComponentPublishLogEntry",
            fields=[
                (
                    "publish_log_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="publishing.publishlogentry",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.component",
                    ),
                ),
                (
                    "component_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.componentversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishedComponent",
            fields=[
                (
                    "component",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="components.component",
                    ),
                ),
                (
                    "component_publish_log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.componentpublishlogentry",
                    ),
                ),
                (
                    "component_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.componentversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.UniqueConstraint(
                fields=("learning_package", "type", "sub_type", "hash_digest"),
                name="content_uniq_lc_hd",
            ),
        ),
        migrations.AddIndex(
            model_name="componentversioncontent",
            index=models.Index(
                fields=["content", "component_version"],
                name="componentversioncontent_c_cv",
            ),
        ),
        migrations.AddIndex(
            model_name="componentversioncontent",
            index=models.Index(
                fields=["component_version", "content"],
                name="componentversioncontent_cv_d",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentversioncontent",
            constraint=models.UniqueConstraint(
                fields=("component_version", "identifier"),
                name="componentversioncontent_uniq_cv_id",
            ),
        ),
        migrations.AddIndex(
            model_name="componentversion",
            index=models.Index(
                fields=["component", "-created"], name="cv_component_rev_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("learning_package", "namespace", "type", "identifier"),
                name="component_uniq_lc_ns_type_identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="publishedcomponent",
            constraint=models.UniqueConstraint(
                fields=("component", "component_version"),
                name="pc_uniq_component_component_version",
            ),
        ),
    ]
