# Generated by Django 4.1 on 2023-02-10 18:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publishing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("namespace", models.CharField(max_length=100)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("identifier", models.CharField(max_length=255)),
                ("created", models.DateTimeField()),
                (
                    "learning_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing.learningpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component",
                "verbose_name_plural": "Components",
            },
        ),
        migrations.CreateModel(
            name="ComponentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=1000)),
                (
                    "version_num",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created", models.DateTimeField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.component",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Version",
                "verbose_name_plural": "Component Versions",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash_digest", models.CharField(editable=False, max_length=40)),
                ("mime_type", models.CharField(max_length=255)),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MaxValueValidator(10000000)]
                    ),
                ),
                ("created", models.DateTimeField()),
                ("data", models.BinaryField(max_length=10000000)),
                (
                    "learning_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing.learningpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentVersionContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "component_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.componentversion",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.content",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="componentversion",
            name="contents",
            field=models.ManyToManyField(
                related_name="component_versions",
                through="components.ComponentVersionContent",
                to="components.content",
            ),
        ),
        migrations.AddField(
            model_name="componentversion",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ComponentPublishLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.component",
                    ),
                ),
                (
                    "component_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.componentversion",
                    ),
                ),
                (
                    "publish_log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing.publishlogentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishedComponent",
            fields=[
                (
                    "component",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="components.component",
                    ),
                ),
                (
                    "component_publish_log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.componentpublishlogentry",
                    ),
                ),
                (
                    "component_version",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="components.componentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Published Component",
                "verbose_name_plural": "Published Components",
            },
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["learning_package", "mime_type"],
                name="content_idx_lp_mime_type",
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["learning_package", "-size"], name="content_idx_lp_rsize"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["learning_package", "-created"], name="content_idx_lp_rcreated"
            ),
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.UniqueConstraint(
                fields=("learning_package", "mime_type", "hash_digest"),
                name="content_uniq_lc_mime_type_hash_digest",
            ),
        ),
        migrations.AddIndex(
            model_name="componentversioncontent",
            index=models.Index(
                fields=["content", "component_version"],
                name="componentversioncontent_c_cv",
            ),
        ),
        migrations.AddIndex(
            model_name="componentversioncontent",
            index=models.Index(
                fields=["component_version", "content"],
                name="componentversioncontent_cv_d",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentversioncontent",
            constraint=models.UniqueConstraint(
                fields=("component_version", "identifier"),
                name="componentversioncontent_uniq_cv_id",
            ),
        ),
        migrations.AddIndex(
            model_name="componentversion",
            index=models.Index(
                fields=["component", "-created"], name="cv_idx_component_rcreated"
            ),
        ),
        migrations.AddIndex(
            model_name="componentversion",
            index=models.Index(fields=["title"], name="cv_idx_title"),
        ),
        migrations.AddConstraint(
            model_name="componentversion",
            constraint=models.UniqueConstraint(
                fields=("component", "version_num"),
                name="cv_uniq_component_version_num",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["learning_package", "identifier"],
                name="component_idx_lp_identifier",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["identifier"], name="component_idx_identifier"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["learning_package", "-created"],
                name="component_idx_lp_rcreated",
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("learning_package", "namespace", "type", "identifier"),
                name="component_uniq_lc_ns_type_identifier",
            ),
        ),
    ]
