# Generated by Django 5.2.11 on 2026-03-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("openedx_content", "0005_containertypes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerContainer",
            fields=[
                (
                    "base_container",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("openedx_content.container",),
        ),
        migrations.CreateModel(
            name="ContainerContainerVersion",
            fields=[
                (
                    "container_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.containerversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("openedx_content.containerversion",),
        ),
        migrations.CreateModel(
            name="TestContainer",
            fields=[
                (
                    "container",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("openedx_content.container",),
        ),
        migrations.CreateModel(
            name="TestContainerVersion",
            fields=[
                (
                    "container_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.containerversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("openedx_content.containerversion",),
        ),
        migrations.CreateModel(
            name="TestEntity",
            fields=[
                (
                    "publishable_entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.publishableentity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestEntityVersion",
            fields=[
                (
                    "publishable_entity_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.publishableentityversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
