# Generated by Django 3.2.23 on 2023-12-07 01:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import openedx_learning.lib.fields
import openedx_learning.lib.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_publishing', '0002_alter_fk_on_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('key', openedx_learning.lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=500)),
                ('title', openedx_learning.lib.fields.MultiCollationCharField(blank=True, db_collations={'mysql': 'utf8mb4_unicode_ci', 'sqlite': 'NOCASE'}, default='', max_length=500)),
                ('created', models.DateTimeField(validators=[openedx_learning.lib.validators.validate_utc_datetime])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('learning_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.learningpackage')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(validators=[openedx_learning.lib.validators.validate_utc_datetime])),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.collection')),
            ],
        ),
        migrations.CreateModel(
            name='RemoveFromCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.collectionchangeset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentity')),
            ],
        ),
        migrations.CreateModel(
            name='PublishEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.collectionchangeset')),
                ('log_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishlogrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionPublishableEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishable_entities', to='oel_collections.collection')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentity')),
            ],
        ),
        migrations.CreateModel(
            name='AddToCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.collectionchangeset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentity')),
                ('published_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentityversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='removefromcollection',
            constraint=models.UniqueConstraint(fields=('change_set', 'entity'), name='oel_collections_refc_uniq_cs_ent'),
        ),
        migrations.AddConstraint(
            model_name='publishentity',
            constraint=models.UniqueConstraint(fields=('change_set', 'log_record'), name='oel_collections_pe_uniq_cs_lr'),
        ),
        migrations.AddConstraint(
            model_name='collectionpublishableentity',
            constraint=models.UniqueConstraint(fields=('collection', 'entity'), name='oel_collections_cpe_uniq_col_ent'),
        ),
        migrations.AddConstraint(
            model_name='collectionchangeset',
            constraint=models.UniqueConstraint(fields=('collection', 'version_num'), name='oel_collections_ccs_uniq_col_vn'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('learning_package', 'key'), name='oel_collections_col_uniq_lp_key'),
        ),
        migrations.AddConstraint(
            model_name='addtocollection',
            constraint=models.UniqueConstraint(fields=('change_set', 'entity'), name='oel_collections_aetc_uniq_cs_ent'),
        ),
    ]
