# Generated by Django 3.2.23 on 2024-01-05 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import openedx_learning.lib.fields
import openedx_learning.lib.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_publishing', '0003_configure_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(validators=[openedx_learning.lib.validators.validate_utc_datetime])),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('key', openedx_learning.lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=500)),
                ('title', openedx_learning.lib.fields.MultiCollationCharField(blank=True, db_collations={'mysql': 'utf8mb4_unicode_ci', 'sqlite': 'NOCASE'}, default='', max_length=500)),
                ('created', models.DateTimeField(validators=[openedx_learning.lib.validators.validate_utc_datetime])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.changeset')),
                ('publish_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishlog')),
            ],
        ),
        migrations.CreateModel(
            name='RemoveEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.changeset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentity')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionPublishableEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.collection')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentity')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='entities',
            field=models.ManyToManyField(related_name='collections', through='oel_collections.CollectionPublishableEntity', to='oel_publishing.PublishableEntity'),
        ),
        migrations.AddField(
            model_name='collection',
            name='learning_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.learningpackage'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_sets', to='oel_collections.collection'),
        ),
        migrations.CreateModel(
            name='AddEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.changeset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentity')),
                ('published_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentityversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='updateentities',
            constraint=models.UniqueConstraint(fields=('change_set', 'publish_log'), name='oel_collections_pe_uniq_cs_pl'),
        ),
        migrations.AddConstraint(
            model_name='removeentity',
            constraint=models.UniqueConstraint(fields=('change_set', 'entity'), name='oel_collections_refc_uniq_cs_ent'),
        ),
        migrations.AddConstraint(
            model_name='collectionpublishableentity',
            constraint=models.UniqueConstraint(fields=('collection', 'entity'), name='oel_collections_cpe_uniq_col_ent'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('learning_package', 'key'), name='oel_collections_col_uniq_lp_key'),
        ),
        migrations.AddConstraint(
            model_name='changeset',
            constraint=models.UniqueConstraint(fields=('collection', 'version_num'), name='oel_collections_ccs_uniq_col_vn'),
        ),
        migrations.AddConstraint(
            model_name='addentity',
            constraint=models.UniqueConstraint(fields=('change_set', 'entity'), name='oel_collections_aetc_uniq_cs_ent'),
        ),
    ]
