# Generated by Django 3.2.23 on 2023-12-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0002_alter_fk_on_delete'),
        ('oel_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='publishable_entities',
            field=models.ManyToManyField(related_name='collection', through='oel_collections.CollectionPublishableEntity', to='oel_publishing.PublishableEntity'),
        ),
        migrations.AlterField(
            model_name='collectionpublishableentity',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.collection'),
        ),
    ]
