# Generated by Django 4.2.16 on 2024-11-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oel_components', '0002_alter_componentversioncontent_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentversioncontent',
            name='learner_downloadable',
        ),
    ]
