# Generated by Django 4.2.23 on 2025-10-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oel_components', '0003_remove_componentversioncontent_learner_downloadable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentversioncontent',
            name='uuid',
        ),
    ]
