# Generated by Django 5.2.9 on 2026-01-09 19:07

from django.db import migrations
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('oel_components', '0004_remove_componentversioncontent_uuid'),
    ]

    operations = [
        SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='component',
                    name='component_type',
                ),
                migrations.RemoveField(
                    model_name='component',
                    name='learning_package',
                ),
                migrations.RemoveField(
                    model_name='component',
                    name='publishable_entity',
                ),
                migrations.RemoveField(
                    model_name='componentversion',
                    name='component',
                ),
                migrations.RemoveField(
                    model_name='componentversion',
                    name='contents',
                ),
                migrations.RemoveField(
                    model_name='componentversion',
                    name='publishable_entity_version',
                ),
                migrations.RemoveField(
                    model_name='componentversioncontent',
                    name='component_version',
                ),
                migrations.RemoveField(
                    model_name='componentversioncontent',
                    name='content',
                ),
                migrations.DeleteModel(
                    name='ComponentType',
                ),
                migrations.DeleteModel(
                    name='Component',
                ),
                migrations.DeleteModel(
                    name='ComponentVersion',
                ),
                migrations.DeleteModel(
                    name='ComponentVersionContent',
                ),
            ]
        )
    ]
