# Generated by Django 5.2.9 on 2026-01-09 19:07

from django.db import migrations
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('oel_units', '0001_initial'),
    ]

    operations = [
        SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='unitversion',
                    name='container_version',
                ),
                migrations.DeleteModel(
                    name='Unit',
                ),
                migrations.DeleteModel(
                    name='UnitVersion',
                ),
            ]
        )
    ]
