# Generated by Django 3.2.13 on 2022-08-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentVersionAsset',
            fields=[
                ('component_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='itemstore.componentversion')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staticassets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
