# Generated by Django 5.2.16 on 2026-08-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_tagging', '0020_tag_depth_and_lineage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyTaxonomy',
            fields=[
                ('taxonomy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oel_tagging.taxonomy')),
            ],
            options={
                'verbose_name': 'Competency Taxonomy',
                'verbose_name_plural': 'Competency Taxonomies',
            },
            bases=('oel_tagging.taxonomy',),
        ),
    ]
