# Generated by Django 5.2.16 on 2026-09-03 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import openedx_django_lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0021_remove_system_defined_add_read_only'),
        ('openedx_learning', '0003_seed_default_rule_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyMasteryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Competency Mastery Status',
                'verbose_name_plural': 'Competency Mastery Statuses',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StudentCompetencyCriteriaGroupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('modified', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('group', models.ForeignKey(db_column='competency_criteria_group_id', on_delete=django.db.models.deletion.PROTECT, related_name='student_statuses', to='openedx_learning.competencycriteriagroup')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_criteria_group_statuses', to='openedx_learning.competencymasterystatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_criteria_group_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Competency Criteria Group Status',
                'verbose_name_plural': 'Student Competency Criteria Group Statuses',
                'constraints': [models.UniqueConstraint(fields=('user', 'group'), name='oex_learning_studentcriteriagroupstatus_user_group_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StudentCompetencyCriteriaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('modified', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('criterion', models.ForeignKey(db_column='competency_criteria_id', on_delete=django.db.models.deletion.PROTECT, related_name='student_statuses', to='openedx_learning.competencycriterion')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_criteria_statuses', to='openedx_learning.competencymasterystatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_criteria_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Competency Criteria Status',
                'verbose_name_plural': 'Student Competency Criteria Statuses',
                'constraints': [models.UniqueConstraint(fields=('user', 'criterion'), name='oex_learning_studentcriteriastatus_user_criterion_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StudentCompetencyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('modified', models.DateTimeField(validators=[openedx_django_lib.validators.validate_utc_datetime])),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_competency_statuses', to='openedx_learning.competencymasterystatus')),
                ('tag', models.ForeignKey(db_column='oel_tagging_tag_id', on_delete=django.db.models.deletion.PROTECT, related_name='student_competency_statuses', to='oel_tagging.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_mastery_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Competency Status',
                'verbose_name_plural': 'Student Competency Statuses',
                'constraints': [models.UniqueConstraint(fields=('user', 'tag'), name='oex_learning_studentcompetencystatus_user_tag_uniq'), models.CheckConstraint(condition=models.Q(('status__in', (2, 3))), name='oex_learning_studentcompetencystatus_status_allowed', violation_error_message='A competency-level status may only be PartiallyAttempted or Demonstrated, since it represents overall demonstration state, not an in-progress state.')],
            },
        ),
    ]
