# Generated by Django 4.2.14 on 2024-08-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0002_alter_learningpackage_key_and_more'),
        ('oel_collections', '0002_remove_collection_name_collection_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_collections.collection')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentity')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='contents',
            field=models.ManyToManyField(related_name='collections', through='oel_collections.CollectionObject', to='oel_publishing.publishableentity'),
        ),
        migrations.AddConstraint(
            model_name='collectionobject',
            constraint=models.UniqueConstraint(fields=('collection', 'object'), name='oel_collections_cpe_uniq_col_obj'),
        ),
    ]
