# Generated by Django 4.2.15 on 2024-09-03 06:25

from django.db import migrations, models
from django.utils.crypto import get_random_string


def generate_slug():
    """
    Generates a random string to initialize a SlugField.

    Used here to initialize Collection.slug, a required field that was added after the model was created.
    """
    return get_random_string(length=50)


class Migration(migrations.Migration):

    dependencies = [
        ('oel_collections', '0003_collection_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=generate_slug),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['learning_package', 'slug'], name='oel_collect_learnin_f23741_idx'),
        ),
    ]
