# Generated by Django 4.2.15 on 2024-09-03 06:25

from django.db import migrations, models
from django.utils.crypto import get_random_string

import openedx_learning.lib.fields


def generate_key():
    """
    Generates a random string to initialize a SlugField.

    Used here to initialize Collection.key, a required field that was added after the model was created.
    """
    return get_random_string(length=50)


class Migration(migrations.Migration):

    dependencies = [
        ('oel_collections', '0003_collection_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='key',
            field=openedx_learning.lib.fields.MultiCollationCharField(
                db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, db_column='_key', max_length=500,
                default=generate_key,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['learning_package', 'key'], name='oel_collect_learnin_f23741_idx'),
        ),
    ]
