# Generated by Django 4.2.15 on 2024-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_collections', '0004_collection_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Disabled collections are "soft deleted", and should be re-enabled before use, or be deleted.'),
        ),
    ]
