# Generated by Django 5.2.12 on 2026-03-24 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_content', '0003_rename_content_to_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='oel_coll_uniq_lp_key',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='key',
            new_name='collection_code',
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('learning_package', 'collection_code'), name='oel_coll_uniq_lp_key'),
        ),
    ]
