# Generated by Django 5.2.11 on 2026-03-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openedx_content", "0003_rename_content_to_media"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="componenttype",
            constraint=models.UniqueConstraint(fields=("namespace", "name"), name="oel_component_type_uniq_ns_n"),
        ),
    ]
