# Generated by Django 5.2.12 on 2026-03-24 20:33

from django.db import migrations

import openedx_django_lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_content', '0004_rename_collection_key_to_code_in_python'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_code',
            field=openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=500),
        ),
    ]
