# Generated by Django 5.2.11 on 2026-03-03 00:54

import django.db.models.deletion
import django.db.models.lookups
from django.db import migrations, models

import openedx_django_lib.fields


def backfill_container_types(apps, schema_editor):
    """
    Fill in the new, mandatory "container_type" foreign key field on all
    existing containers.
    """
    Container = apps.get_model("openedx_content", "Container")
    ContainerType = apps.get_model("openedx_content", "ContainerType")
    section_type, _ = ContainerType.objects.get_or_create(type_code="section")
    subsection_type, _ = ContainerType.objects.get_or_create(type_code="subsection")
    unit_type, _ = ContainerType.objects.get_or_create(type_code="unit")

    containers_to_update = Container.objects.filter(container_type=None)

    containers_to_update.exclude(section=None).update(container_type=section_type)
    containers_to_update.exclude(subsection=None).update(container_type=subsection_type)
    containers_to_update.exclude(unit=None).update(container_type=unit_type)

    unknown_containers = containers_to_update.all()
    if unknown_containers:
        raise ValueError(f"container {unknown_containers[0]} is of unknown container type. Cannot apply migration.")


class Migration(migrations.Migration):
    dependencies = [
        ("openedx_content", "0004_componenttype_constraint"),
    ]

    operations = [
        # 1. Create the new ContainerType model
        migrations.CreateModel(
            name="ContainerType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_code",
                    openedx_django_lib.fields.MultiCollationCharField(
                        db_collations={"mysql": "utf8mb4_bin", "sqlite": "BINARY"}, max_length=100, unique=True
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.Regex(models.F("type_code"), "^[a-z0-9\\-_\\.]+$"),
                        name="oex_publishing_containertype_type_code_rx",
                    )
                ],
            },
        ),
        # 2. Define the ForeignKey from Container to ContainerType
        migrations.AddField(
            model_name="container",
            name="container_type",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="openedx_content.containertype",
            ),
        ),
        # 3. Populate the container_type column, which is currently NULL for all existing containers
        migrations.RunPython(backfill_container_types),
        # 4. disallow NULL values from now on
        migrations.AlterField(
            model_name="container",
            name="container_type",
            field=models.ForeignKey(
                editable=False,
                null=False,
                on_delete=django.db.models.deletion.RESTRICT,
                to="openedx_content.containertype",
            ),
        ),
    ]
