# Generated by Django 5.2.11 on 2026-04-08 17:49

import openedx_content.applets.publishing.models.id_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openedx_content", "0005_containertypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningpackage",
            name="id",
            field=openedx_content.applets.publishing.models.id_fields.LearningPackagePKField(
                primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="publishableentity",
            name="id",
            field=openedx_content.applets.publishing.models.id_fields.PublishableEntityPKField(
                primary_key=True, serialize=False
            ),
        ),
    ]
