# Generated by Django 5.2.13 on 2026-04-13 21:28

from django.db import migrations, models


def backfill_direct_to_none(apps, schema_editor):
    """
    Set direct=None for all pre-existing PublishLogRecords so they are treated
    as historical records whose user intent cannot be determined retroactively.
    New records created after this migration will default to direct=False.
    """
    PublishLogRecord = apps.get_model('openedx_content', 'PublishLogRecord')
    PublishLogRecord.objects.update(direct=None)


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_content', '0006_typed_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishlogrecord',
            name='direct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.RunPython(
            backfill_direct_to_none,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
