# Generated by Django 5.2.13 on 2026-04-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_content', '0006_typed_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishlogrecord',
            name='direct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
