# Generated by Django 5.2.12 on 2026-03-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_content', '0005_containertypes'),
        ('openedx_content', '0006_add_collection_code_regex_validation'),
    ]

    operations = [
    ]
