# Generated by Django 5.2.13 on 2026-04-23 14:15

import re

import django.core.validators
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models

import openedx_django_lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_content', '0012_rename_componentversionmedia_key_to_path'),
    ]

    operations = [
        # For the vast majority of sites, re-creating these constraints is redundant with
        # 0009-0010. But, a handful of developers had applied 0009 and 0010 when they contained
        # ascii-only constraints. Re-creating the constraints here ensure that everyone's on
        # the same page with identical, unicode-friendly constraints.
        migrations.RemoveConstraint(
            model_name='component',
            name='oel_component_code_regex',
        ),
        migrations.RemoveConstraint(
            model_name='container',
            name='oel_container_code_regex',
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_code',
            field=openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_.-]+\\Z'), 'Enter a valid "code name" consisting of latin letters (A-Z, a-z), numbers, underscores, hyphens, or periods.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_code',
            field=openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.-]+\\Z'), 'Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_code',
            field=openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.-]+\\Z'), 'Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.', 'invalid')]),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Regex(models.F('component_code'), '^[\\w.-]+\\Z'), name='oel_component_code_regex', violation_error_message='Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.'),
        ),
        migrations.AddConstraint(
            model_name='container',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Regex(models.F('container_code'), '^[\\w.-]+\\Z'), name='oel_container_code_regex', violation_error_message='Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.'),
        ),
        migrations.AlterConstraint(
            model_name='collection',
            name='oel_coll_collection_code_regex',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Regex(models.F('collection_code'), '^[a-zA-Z0-9_.-]+\\Z'), name='oel_coll_collection_code_regex', violation_error_message='Enter a valid "code name" consisting of latin letters (A-Z, a-z), numbers, underscores, hyphens, or periods.'),
        ),
    ]
