# Generated by Django 5.2.12 on 2026-04-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Media.id was previously auto-created by Django (hence auto_created=True,
    verbose_name='ID' in the original migration). It is now explicitly declared
    on the model. The database column is unchanged (still BIGINT AUTO_INCREMENT
    PRIMARY KEY), so database_operations is empty.
    """
    dependencies = [
        ('openedx_content', '0013_unicode_container_component_codes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='media',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            database_operations=[],
        )
    ]
