# Generated by Django 5.2.13 on 2026-06-01 02:40

import django.core.validators
import django.db.models.deletion
import django.db.models.lookups
import openedx_django_lib.fields
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_content', '0014_typed_media_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('publishable_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openedx_content.publishableentity')),
                ('asset_code', openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.-]+\\Z'), 'Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.', 'invalid')])),
                ('learning_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedx_content.learningpackage')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetBundleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=100, unique=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.Regex(models.F('code'), '^[a-z0-9\\-_\\.]+$'), name='oel_assetbundletype_code_rx')],
            },
        ),
        migrations.CreateModel(
            name='AssetBundle',
            fields=[
                ('publishable_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openedx_content.publishableentity')),
                ('bundle_code', openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.-]+\\Z'), 'Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.', 'invalid')])),
                ('learning_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedx_content.learningpackage')),
                ('asset_bundle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='openedx_content.assetbundletype')),
            ],
            options={
                'verbose_name': 'Asset Bundle',
                'verbose_name_plural': 'Asset Bundles',
            },
        ),
        migrations.CreateModel(
            name='AssetBundleVersion',
            fields=[
                ('publishable_entity_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openedx_content.publishableentityversion')),
                ('asset_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='openedx_content.assetbundle')),
            ],
            options={
                'verbose_name': 'Asset Bundle Version',
                'verbose_name_plural': 'Asset Bundle Versions',
            },
        ),
        migrations.CreateModel(
            name='AssetBundleVersionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='openedx_content.asset')),
                ('asset_bundle_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedx_content.assetbundleversion')),
            ],
        ),
        migrations.AddField(
            model_name='assetbundleversion',
            name='assets',
            field=models.ManyToManyField(related_name='bundle_versions', through='openedx_content.AssetBundleVersionAsset', to='openedx_content.asset'),
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=100, unique=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.Regex(models.F('code'), '^[a-z0-9\\-_\\.]+$'), name='oel_assettype_code_rx')],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='openedx_content.assettype'),
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('publishable_entity_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='openedx_content.publishableentityversion')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='openedx_content.asset')),
            ],
            options={
                'verbose_name': 'Asset Version',
                'verbose_name_plural': 'Asset Versions',
            },
        ),
        migrations.CreateModel(
            name='AssetVersionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', openedx_django_lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, max_length=500)),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedx_content.assetversion')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='openedx_content.media')),
            ],
        ),
        migrations.AddField(
            model_name='assetversion',
            name='media',
            field=models.ManyToManyField(related_name='asset_versions', through='openedx_content.AssetVersionMedia', to='openedx_content.media'),
        ),
        migrations.AddIndex(
            model_name='assetbundle',
            index=models.Index(fields=['asset_bundle_type', 'bundle_code'], name='oel_assetbundle_idx_abt_code'),
        ),
        migrations.AddConstraint(
            model_name='assetbundle',
            constraint=models.UniqueConstraint(fields=('learning_package', 'asset_bundle_type', 'bundle_code'), name='oel_assetbundle_uniq_lp_abt_code'),
        ),
        migrations.AddConstraint(
            model_name='assetbundle',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Regex(models.F('bundle_code'), '^[\\w.-]+\\Z'), name='oel_assetbundle_code_regex', violation_error_message='Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.'),
        ),
        migrations.AddIndex(
            model_name='assetbundleversionasset',
            index=models.Index(fields=['asset', 'asset_bundle_version'], name='oel_abva_asset_abv'),
        ),
        migrations.AddConstraint(
            model_name='assetbundleversionasset',
            constraint=models.UniqueConstraint(fields=('asset_bundle_version', 'asset'), name='oel_abva_uniq_abv_asset'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'asset_code'], name='oel_asset_idx_at_code'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('learning_package', 'asset_type', 'asset_code'), name='oel_asset_uniq_lp_at_code'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Regex(models.F('asset_code'), '^[\\w.-]+\\Z'), name='oel_asset_code_regex', violation_error_message='Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.'),
        ),
        migrations.AddIndex(
            model_name='assetversionmedia',
            index=models.Index(fields=['media', 'asset_version'], name='oel_avmedia_m_av'),
        ),
        migrations.AddIndex(
            model_name='assetversionmedia',
            index=models.Index(fields=['asset_version', 'media'], name='oel_avmedia_av_m'),
        ),
        migrations.AddConstraint(
            model_name='assetversionmedia',
            constraint=models.UniqueConstraint(fields=('asset_version', 'variant'), name='oel_avmedia_uniq_av_variant'),
        ),
    ]
