# Generated by Django 5.2.9 on 2025-12-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oel_components', '0004_remove_componentversioncontent_uuid'),
        ('oel_contents', '0001_initial'),
        ('oel_publishing', '0010_backfill_dependencies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Media',
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
    ]
