# Generated by Django 5.2.9 on 2025-12-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_contents', '0002_rename_content_media'),
        ('oel_publishing', '0010_backfill_dependencies'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='media',
            name='oel_content_uniq_lc_media_type_hash_digest',
        ),
        migrations.RenameIndex(
            model_name='media',
            new_name='oel_media_idx_lp_rsize',
            old_name='oel_content_idx_lp_rsize',
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(fields=('learning_package', 'media_type', 'hash_digest'), name='oel_media_uniq_lc_media_type_hash_digest'),
        ),
    ]
