# Generated by Django 4.1.6 on 2023-04-14 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openedx_learning.lib.validators
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=1000)),
                (
                    "created",
                    models.DateTimeField(
                        validators=[
                            openedx_learning.lib.validators.validate_utc_datetime
                        ]
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        validators=[
                            openedx_learning.lib.validators.validate_utc_datetime
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Package",
                "verbose_name_plural": "Learning Packages",
            },
        ),
        migrations.CreateModel(
            name="PublishLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=1000)),
                (
                    "published_at",
                    models.DateTimeField(
                        validators=[
                            openedx_learning.lib.validators.validate_utc_datetime
                        ]
                    ),
                ),
                (
                    "learning_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing.learningpackage",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publish Log Entry",
                "verbose_name_plural": "Publish Log Entries",
            },
        ),
        migrations.AddConstraint(
            model_name="learningpackage",
            constraint=models.UniqueConstraint(
                fields=("identifier",), name="lp_uniq_identifier"
            ),
        ),
    ]
