# Generated by Django 3.2.10 on 2022-07-17 01:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningContextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField()),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishing.learningcontext')),
                ('prev_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='publishing.learningcontext')),
            ],
        ),
        migrations.AddConstraint(
            model_name='learningcontext',
            constraint=models.UniqueConstraint(fields=('identifier',), name='lc_uniq_identifier'),
        ),
    ]
