# Generated by Django 4.1 on 2023-02-06 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=1000)),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PublishLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("published_at", models.DateTimeField()),
                (
                    "learning_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishing.learningpackage",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="learningpackage",
            constraint=models.UniqueConstraint(
                fields=("identifier",), name="lp_uniq_identifier"
            ),
        ),
    ]
