# Generated by Django 3.2.21 on 2023-10-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Make it so that Draft and Published cascade deletes from PublishableEntity.

    This makes it so that deleting a LearningPackage properly cleans up these
    models as well.
    """

    dependencies = [
        ('oel_publishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oel_publishing.publishableentity'),
        ),
        migrations.AlterField(
            model_name='published',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oel_publishing.publishableentity'),
        ),
    ]
