# Generated by Django 3.2.10 on 2022-08-14 04:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontextversion',
            name='prev_version',
        ),
        migrations.AlterField(
            model_name='learningcontext',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='learningcontextversion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
