# Generated by Django 3.2.19 on 2023-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oel_publishing", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="publishlogrecord",
            index=models.Index(
                fields=["entity", "-publish_log"], name="oel_plr_idx_entity_rplr"
            ),
        ),
        migrations.AddConstraint(
            model_name="publishlogrecord",
            constraint=models.UniqueConstraint(
                fields=("publish_log", "entity"), name="oel_plr_uniq_pl_publishable"
            ),
        ),
    ]
