# Generated by Django 5.2.9 on 2026-01-09 19:07

from django.db import migrations
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('oel_collections', '0005_alter_collection_options_alter_collection_enabled'),
    ]

    operations = [
        SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='collectionpublishableentity',
                    name='collection',
                ),
                migrations.RemoveField(
                    model_name='collectionpublishableentity',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='collectionpublishableentity',
                    name='entity',
                ),
                migrations.DeleteModel(
                    name='Collection',
                ),
                migrations.DeleteModel(
                    name='CollectionPublishableEntity',
                ),
            ]
        )
    ]