# Generated by Django 4.2.18 on 2025-03-10 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openedx_learning.lib.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oel_publishing', '0003_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('change_set_type', models.SmallIntegerField(choices=[(0, 'Migration Initialization'), (1, 'Create'), (2, 'Edit'), (3, 'Delete'), (4, 'Reset to Published')], default=2)),
                ('changed_at', models.DateTimeField(validators=[openedx_learning.lib.validators.validate_utc_datetime])),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('learning_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.learningpackage')),
            ],
            options={
                'verbose_name': 'Draft Change Set',
                'verbose_name_plural': 'Draft Change Sets',
            },
        ),
        migrations.CreateModel(
            name='DraftChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='oel_publishing.draftchangeset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.publishableentity')),
                ('new_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.publishableentityversion')),
                ('old_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='oel_publishing.publishableentityversion')),
            ],
            options={
                'verbose_name': 'Draft Change',
                'verbose_name_plural': 'Draft Changes',
                'indexes': [models.Index(fields=['entity', '-change_set'], name='oel_dc_idx_entity_rchangeset')],
            },
        ),
        migrations.AddConstraint(
            model_name='draftchange',
            constraint=models.UniqueConstraint(fields=('change_set', 'entity'), name='oel_dc_uniq_changeset_entity'),
        ),
    ]
