# Generated by Django 4.2.19 on 2025-03-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0003_containers'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishableentity',
            name='can_stand_alone',
            field=models.BooleanField(
                default=True,
                help_text="Set to True when created independently, False when created as part of a container.",
            ),
        ),
    ]
