# Generated by Django 4.2.20 on 2025-04-17 18:22
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0007_bootstrap_draftchangelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftchangelogrecord',
            options={'verbose_name': 'Draft Change Log Record', 'verbose_name_plural': 'Draft Change Log Records'},
        ),
        migrations.AlterModelOptions(
            name='draftsideeffect',
            options={'verbose_name': 'Draft Side Effect', 'verbose_name_plural': 'Draft Side Effects'},
        ),
        migrations.AlterField(
            model_name='draftchangelogrecord',
            name='draft_change_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='oel_publishing.draftchangelog'),
        ),
        migrations.AlterField(
            model_name='draftsideeffect',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='affected_by', to='oel_publishing.draftchangelogrecord'),
        ),
    ]
