# Generated by Django 4.2.16 on 2025-04-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oel_publishing", "0008_alter_draftchangelogrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="draftchangelogrecord",
            options={
                "verbose_name": "Draft Change Log Record",
                "verbose_name_plural": "Draft Change Log Records",
            },
        ),
        migrations.AlterModelOptions(
            name="draftsideeffect",
            options={
                "verbose_name": "Draft Side Effect",
                "verbose_name_plural": "Draft Side Effects",
            },
        ),
        migrations.AlterField(
            model_name="draftchangelogrecord",
            name="draft_change_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="oel_publishing.draftchangelog",
            ),
        ),
        migrations.AlterField(
            model_name="draftsideeffect",
            name="effect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="affected_by",
                to="oel_publishing.draftchangelogrecord",
            ),
        ),
        migrations.CreateModel(
            name="PublishSideEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="causes",
                        to="oel_publishing.publishlogrecord",
                    ),
                ),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="affected_by",
                        to="oel_publishing.publishlogrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publish Side Effect",
                "verbose_name_plural": "Publish Side Effects",
            },
        ),
        migrations.AddConstraint(
            model_name="publishsideeffect",
            constraint=models.UniqueConstraint(
                fields=("cause", "effect"), name="oel_pub_pse_uniq_c_e"
            ),
        ),
    ]
