# Generated by Django 5.2.7 on 2025-10-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0008_alter_draftchangelogrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='draft_log_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oel_publishing.draftchangelogrecord'),
        ),
        migrations.AddField(
            model_name='draftchangelogrecord',
            name='dependencies_hash_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='publishlogrecord',
            name='dependencies_hash_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=8),
        ),
        migrations.CreateModel(
            name='PublishableEntityVersionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenced_entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.publishableentity')),
                ('referring_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.publishableentityversion')),
            ],
        ),
        migrations.AddField(
            model_name='publishableentityversion',
            name='dependencies',
            field=models.ManyToManyField(related_name='affects', through='oel_publishing.PublishableEntityVersionDependency', to='oel_publishing.publishableentity'),
        ),
        migrations.CreateModel(
            name='PublishSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='causes', to='oel_publishing.publishlogrecord')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='affected_by', to='oel_publishing.publishlogrecord')),
            ],
            options={
                'verbose_name': 'Publish Side Effect',
                'verbose_name_plural': 'Publish Side Effects',
            },
        ),
        migrations.AddConstraint(
            model_name='publishableentityversiondependency',
            constraint=models.UniqueConstraint(fields=('referring_version', 'referenced_entity'), name='oel_pevd_uniq_rv_re'),
        ),
        migrations.AddConstraint(
            model_name='publishsideeffect',
            constraint=models.UniqueConstraint(fields=('cause', 'effect'), name='oel_pub_pse_uniq_c_e'),
        ),
    ]
