# Generated by Django 4.2.23 on 2025-08-27 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0008_alter_draftchangelogrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='dependencies_hash_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='published',
            name='dependencies_hash_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=8),
        ),
        migrations.CreateModel(
            name='PublishSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='causes', to='oel_publishing.publishlogrecord')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='affected_by', to='oel_publishing.publishlogrecord')),
            ],
            options={
                'verbose_name': 'Publish Side Effect',
                'verbose_name_plural': 'Publish Side Effects',
            },
        ),
        migrations.CreateModel(
            name='PublishableEntityVersionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.publishableentity')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='oel_publishing.publishableentityversion')),
            ],
        ),
        migrations.AddField(
            model_name='publishableentityversion',
            name='dependencies',
            field=models.ManyToManyField(related_name='affects', through='oel_publishing.PublishableEntityVersionDependency', to='oel_publishing.publishableentity'),
        ),
        migrations.AddConstraint(
            model_name='publishsideeffect',
            constraint=models.UniqueConstraint(fields=('cause', 'effect'), name='oel_pub_pse_uniq_c_e'),
        ),
        migrations.AddConstraint(
            model_name='publishableentityversiondependency',
            constraint=models.UniqueConstraint(fields=('version', 'entity'), name='oel_pevd_uniq_version_entity'),
        ),
    ]
