# Generated by Django 4.2.21 on 2025-06-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0009_create_publishsideeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='state_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=40),
        ),
        migrations.CreateModel(
            name='DraftDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes_side_effects_for', to='oel_publishing.draft')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='oel_publishing.draft')),
                ('version_at_creation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='draft_dependencies_created', to='oel_publishing.publishableentityversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='draftdependency',
            constraint=models.UniqueConstraint(fields=('draft', 'dependency'), name='oel_pub_dd_uniq_draft_dep'),
        ),
    ]
