# Generated by Django 5.2.7 on 2025-10-28 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0009_draft_draft_log_record_and_dependency_hashing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='draft_log_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oel_publishing.draftchangelogrecord'),
        ),
    ]
