# Generated by Django 4.2.21 on 2025-06-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0010_draft_dependency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='draftdependency',
            name='oel_pub_dd_uniq_draft_dep',
        ),
        migrations.RenameField(
            model_name='draftdependency',
            old_name='draft',
            new_name='target',
        ),
        migrations.AddConstraint(
            model_name='draftdependency',
            constraint=models.UniqueConstraint(fields=('target', 'dependency'), name='oel_pub_dd_uniq_target_dep'),
        ),
    ]
