# Generated by Django 3.2.19 on 2023-07-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="system_defined",
            field=models.BooleanField(
                default=False,
                help_text="Indicates that tags and metadata for this taxonomy are maintained by the system; taxonomy admins will not be permitted to modify them.",
            ),
        ),
    ]
