# Generated by Django 3.2.19 on 2023-06-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemTaxonomy",
            fields=[
                (
                    "taxonomy_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="oel_tagging.taxonomy",
                    ),
                ),
            ],
            bases=("oel_tagging.taxonomy",),
        ),
    ]
