# Generated by Django 3.2.19 on 2023-06-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objecttag',
            index=models.Index(fields=['taxonomy', 'object_id'], name='oel_tagging_taxonom_aa24e6_idx'),
        ),
    ]
