# Generated by Django 3.2.19 on 2023-06-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0001_squashed'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='objecttag',
            index_together={('taxonomy', '_value')},
        ),
    ]
