# Generated by Django 3.2.19 on 2023-07-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTaxonomy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oel_tagging.taxonomy',),
        ),
    ]
