# Generated by Django 3.2.19 on 2023-07-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0002_auto_20230718_2026"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="objecttag",
            unique_together={("taxonomy", "_value", "object_id")},
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("taxonomy", "value")},
        ),
        migrations.AddIndex(
            model_name="objecttag",
            index=models.Index(
                fields=["taxonomy", "object_id"], name="oel_tagging_taxonom_aa24e6_idx"
            ),
        ),
    ]
