# Generated by Django 3.2.19 on 2023-07-04 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0002_systemtaxonomy"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="objecttag",
            name="oel_tagging_taxonom_3668ec_idx",
        ),
        migrations.RenameField(
            model_name="objecttag",
            old_name="taxonomy",
            new_name="_taxonomy",
        ),
        migrations.AddIndex(
            model_name="objecttag",
            index=models.Index(
                fields=["_taxonomy", "_value"], name="oel_tagging__taxono_af4c8a_idx"
            ),
        ),
    ]
