# Generated by Django 3.2.19 on 2023-07-06 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0003_objecttag_proxies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="parent",
            field=models.ForeignKey(
                default=None,
                help_text="Tag that lives one level up from the current tag, forming a hierarchy.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="oel_tagging.tag",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="taxonomy",
            field=models.ForeignKey(
                default=None,
                help_text="Namespace and rules for using a given set of tags.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="oel_tagging.taxonomy",
            ),
        ),
    ]
