# Generated by Django 3.2.19 on 2023-07-24 06:25

from django.db import migrations, models

import openedx_learning.lib.fields


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0003_auto_20230721_1238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objecttag",
            name="object_id",
            field=openedx_learning.lib.fields.MultiCollationCharField(
                db_collations={"mysql": "utf8mb4_unicode_ci", "sqlite": "NOCASE"},
                db_index=True,
                editable=False,
                help_text="Identifier for the object being tagged",
                max_length=255,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("taxonomy", "external_id"), ("taxonomy", "value")},
        ),
        migrations.AddIndex(
            model_name="objecttag",
            index=models.Index(
                fields=["taxonomy", "object_id"], name="oel_tagging_taxonom_aa24e6_idx"
            ),
        ),
    ]
