# Generated by Django 3.2.19 on 2023-07-28 13:33

from django.core.management import call_command
from django.db import migrations


def load_language_taxonomy(apps, schema_editor):
    """
    Load language taxonomy and tags
    """
    # Due to changes in the data model this fixture was no longer working and is
    # no longer needed anyways - the language taxonomy will be created in
    # 0012_language_taxonomy.
    pass


def revert(apps, schema_editor):  # pragma: no cover
    """
    Deletes language taxonomy an tags
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0004_auto_20230723_2001"),
    ]

    operations = [
        migrations.RunPython(load_language_taxonomy, revert),
    ]
