# Generated by Django 3.2.19 on 2023-07-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0004_tag_cascade_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="visible_to_authors",
            field=models.BooleanField(
                default=True,
                editable=False,
                help_text="Indicates whether this taxonomy should be visible to object authors.",
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="system_defined",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Indicates that tags and metadata for this taxonomy are maintained by the system; taxonomy admins will not be permitted to modify them.",
            ),
        ),
    ]
