# Generated by Django 3.2.19 on 2023-07-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0005_auto_20230710_0140"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClosedObjectTag",
        ),
        migrations.DeleteModel(
            name="OpenObjectTag",
        ),
        migrations.RemoveField(
            model_name="taxonomy",
            name="_object_tag_class",
        ),
        migrations.AddField(
            model_name="objecttag",
            name="_object_tag_class",
            field=models.CharField(
                help_text="Overrides the ObjectTag subclass used to instantiate this ObjectTag.Must be a fully-qualified module and class name.",
                max_length=255,
                null=True,
            ),
        ),
    ]
