# Generated by Django 3.2.20 on 2023-08-23 18:14

from django.db import migrations

import openedx_learning.lib.fields


class Migration(migrations.Migration):
    dependencies = [
        ("oel_tagging", "0007_tag_import_task_log_null_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxonomy",
            name="description",
            field=openedx_learning.lib.fields.MultiCollationTextField(
                blank=True,
                default="",
                help_text="Provides extra information for the user when applying tags from this taxonomy to an object.",
            ),
            preserve_default=False,
        ),
    ]
