# Generated by Django 3.2.19 on 2023-09-26 13:36

from django.db import migrations

import openedx_learning.lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0008_taxonomy_description_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttag',
            name='object_id',
            field=openedx_learning.lib.fields.MultiCollationCharField(db_collations={'mysql': 'utf8mb4_bin', 'sqlite': 'BINARY'}, db_index=True, editable=False, help_text='Identifier for the object being tagged', max_length=255),
        ),
    ]
