# Generated by Django 3.2.19 on 2023-10-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0010_cleanups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='required',
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='allow_multiple',
            field=models.BooleanField(default=True, help_text='Indicates that multiple tags from this taxonomy may be added to an object.'),
        ),
    ]
