# Generated by Django 4.2.16 on 2024-10-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0017_alter_tagimporttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttag',
            name='read_only',
            field=models.BooleanField(default=False, help_text='True if this object tag cannot be deleted by the user.'),
        ),
    ]
