# Generated by Django 4.2.16 on 2024-10-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0017_alter_tagimporttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttag',
            name='is_copied',
            field=models.BooleanField(default=False, help_text="True if this object tag has been copied from one object to another using 'copy_tags' api function"),
        ),
    ]
