# Generated by Django 3.2.10 on 2022-05-07 19:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAtom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_digest', models.CharField(editable=False, max_length=40)),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('created', models.DateTimeField()),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearningContextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_num', models.PositiveIntegerField()),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.learningcontext')),
            ],
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(max_length=255)),
                ('currently_published', models.BooleanField()),
                ('last_published', models.DateTimeField(null=True)),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.learningcontext')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleContentObject',
            fields=[
                ('content_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learning_publishing.contentobject')),
            ],
        ),
        migrations.CreateModel(
            name='LearningItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='learning_publishing.contentobject')),
                ('learning_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.learningitem')),
            ],
        ),
        migrations.CreateModel(
            name='LearningContextVersionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning_publishing.learningitemversion')),
                ('learning_context_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.learningcontextversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='learningcontext',
            constraint=models.UniqueConstraint(fields=('identifier',), name='learning_publishing_lc_uniq_identifier'),
        ),
        migrations.AddField(
            model_name='contentpackage',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.learningcontext'),
        ),
        migrations.AddField(
            model_name='contentatom',
            name='content_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.contentpackage'),
        ),
        migrations.AddField(
            model_name='simplecontentobject',
            name='content_atom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='learning_publishing.contentatom'),
        ),
        migrations.AddConstraint(
            model_name='learningitem',
            constraint=models.UniqueConstraint(fields=('learning_context_id', 'identifier'), name='learning_publishing_lcb_one_identifier_per_lc'),
        ),
        migrations.AddConstraint(
            model_name='learningcontextversion',
            constraint=models.UniqueConstraint(fields=('learning_context_id', 'version_num'), name='learning_publishing_lcv_uniq_lc_vn'),
        ),
        migrations.AddConstraint(
            model_name='contentatom',
            constraint=models.UniqueConstraint(fields=('content_package_id', 'mime_type', 'hash_digest'), name='learning_publishing_ca_uniq_cp_mt_hd'),
        ),
    ]
