# Generated by Django 3.2.10 on 2022-04-26 09:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(help_text="Major types include 'block', 'unit', and 'sequence'.", max_length=50)),
                ('minor', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContentAtom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_digest', models.CharField(editable=False, max_length=40)),
                ('mime_type', models.CharField(max_length=255)),
                ('text_data', models.TextField(null=True)),
                ('json_data', models.JSONField(null=True)),
                ('bin_data', models.BinaryField(null=True)),
                ('size', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('segment_order_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentObjectPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearningContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearningContextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_num', models.PositiveIntegerField()),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.learningcontext')),
            ],
        ),
        migrations.AddConstraint(
            model_name='learningcontext',
            constraint=models.UniqueConstraint(fields=('identifier',), name='learning_publishing_lc_uniq_identifier'),
        ),
        migrations.AddField(
            model_name='contentpackage',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.learningcontext'),
        ),
        migrations.AddField(
            model_name='contentobjectpart',
            name='content_atom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='learning_publishing.contentatom'),
        ),
        migrations.AddField(
            model_name='contentobjectpart',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.contentobject'),
        ),
        migrations.AddField(
            model_name='contentobject',
            name='content_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.contentsegment'),
        ),
        migrations.AddField(
            model_name='contentatom',
            name='content_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_publishing.contentpackage'),
        ),
        migrations.AddConstraint(
            model_name='learningcontextversion',
            constraint=models.UniqueConstraint(fields=('learning_context_id', 'version_num'), name='learning_publishing_lcv_uniq_lc_vn'),
        ),
        migrations.AddConstraint(
            model_name='contentobjectpart',
            constraint=models.UniqueConstraint(fields=('content_object_id', 'identifier'), name='learning_publishing_cop_uniq_co_identifier'),
        ),
        migrations.AddConstraint(
            model_name='contentobject',
            constraint=models.UniqueConstraint(fields=('content_segment_id', 'segment_order_num'), name='learning_publishing_co_uniq_cs_son'),
        ),
        migrations.AddConstraint(
            model_name='contentatom',
            constraint=models.UniqueConstraint(fields=('content_package_id', 'hash_digest'), name='learning_publishing_ca_uniq_cp_hd'),
        ),
    ]
