# Generated by Django 3.2.10 on 2022-05-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockContentObject',
            fields=[
                ('simple_content_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learning_publishing.simplecontentobject')),
                ('type', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaticAssetContentObject',
            fields=[
                ('simple_content_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learning_publishing.simplecontentobject')),
            ],
        ),
    ]
