# Generated by Django 4.2.16 on 2024-10-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_containers', '0001_initial'),
        ('oel_publishing', '0002_alter_learningpackage_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('publishable_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oel_publishing.publishableentity')),
                ('container_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oel_containers.containerentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitVersion',
            fields=[
                ('publishable_entity_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oel_publishing.publishableentityversion')),
                ('container_entity_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oel_containers.containerentityversion')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='oel_units.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
