# Generated by Django 4.2.20 on 2025-04-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitversion',
            name='enable_discussion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unitversion',
            name='hide_from_learners',
            field=models.BooleanField(default=False),
        ),
    ]
