name: Python CI

on:
  push:
    branches: [main]
  workflow_call:
  pull_request:
    branches:
      - '**'


jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # Add macos-latest later?
        python-version: ['3.12']
        toxenv: ["django52", "package", "quality", "docs"]
        mysql-version: ["8"]
    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: "test_oel_db"
          MYSQL_USER: "test_oel_user"
          MYSQL_PASSWORD: "test_oel_pass"
          MYSQL_RANDOM_ROOT_PASSWORD: true
        # these options are blatantly copied from edx-platform's values
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install CI dependencies
        run: uv sync --group ci

      - name: Run Tests
        run: uv run tox -e ${{ matrix.toxenv }}
