# Generated by Django 5.2.9 on 2025-12-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oel_components', '0004_remove_componentversioncontent_uuid'),
        ('oel_contents', '0003_rename_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentVersionContent',
            new_name='ComponentVersionMedia',
        ),
    ]
