# Generated by Django 5.2.9 on 2025-12-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_components', '0005_rename_componentversioncontent_componentversionmedia'),
        ('oel_contents', '0003_rename_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='componentversionmedia',
            name='oel_cvcontent_uniq_cv_key',
        ),
        migrations.RemoveIndex(
            model_name='componentversionmedia',
            name='oel_cvcontent_c_cv',
        ),
        migrations.RemoveIndex(
            model_name='componentversionmedia',
            name='oel_cvcontent_cv_d',
        ),
        migrations.RenameField(
            model_name='componentversion',
            old_name='contents',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='componentversionmedia',
            old_name='content',
            new_name='media',
        ),
        migrations.AddIndex(
            model_name='componentversionmedia',
            index=models.Index(fields=['media', 'component_version'], name='oel_cvmediat_c_cv'),
        ),
        migrations.AddIndex(
            model_name='componentversionmedia',
            index=models.Index(fields=['component_version', 'media'], name='oel_cvmedia_cv_d'),
        ),
        migrations.AddConstraint(
            model_name='componentversionmedia',
            constraint=models.UniqueConstraint(fields=('component_version', 'key'), name='oel_cvmedia_uniq_cv_key'),
        ),
    ]
